//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionInmobiliaria {
	
	
	public partial class ContentPropiedad {
		
		protected System.Web.UI.WebControls.Content OwnershipContent;
		
		protected System.Web.UI.WebControls.LinkButton @return;
		
		protected System.Web.UI.WebControls.Label LabelDireccion;
		
		protected System.Web.UI.WebControls.Label LabelCaracteristicas;
		
		protected System.Web.UI.WebControls.Label LabelPrecio;
		
		protected System.Web.UI.WebControls.LinkButton contactSeller;
	}
}
