//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionInmobiliaria {
	
	
	public partial class Login {
		
		protected System.Web.UI.WebControls.Content LoginContent;
		
		protected System.Web.UI.HtmlControls.HtmlForm formLogin;
		
		protected System.Web.UI.WebControls.Button buttonLogin;
		
		protected System.Web.UI.WebControls.Button buttonRegisterBuyer;
		
		protected System.Web.UI.WebControls.Button buttonRegisterSeller;
	}
}
