//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionInmobiliaria {
	
	
	public partial class Master {
		
		protected System.Web.UI.WebControls.LinkButton brand;
		
		protected System.Web.UI.WebControls.LinkButton link0;
		
		protected System.Web.UI.WebControls.LinkButton link1;
		
		protected System.Web.UI.WebControls.LinkButton link2;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder contentPlaceHolder;
	}
}
