//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionInmobiliaria {
	
	
	public partial class Search {
		
		protected System.Web.UI.WebControls.Content MainContent;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button buttonLogin;
		
		protected System.Web.UI.WebControls.DropDownList ddlNameCity;
		
		protected System.Web.UI.WebControls.Button buttonSearch;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder carouselPlaceHolder;
	}
}
